services:
  dashboard:
    build: .
    environment:
      ADMIN_PASSWORD: "Suporte@2026"
    ports:
      - "8085:8085"
    volumes:
      - dashboard_storage:/app/storage

volumes:
  dashboard_storage:
